version: 2

jobs:
  "php-8.1":
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

  "php-8.2":
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

workflows:
    version: 2
    build:
        jobs:
            - "php-8.1"
            - "php-8.2"
