version: 2

jobs:
  "php-7.2":
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

  "php-8.0":
    docker:
      - image: circleci/php:8.0
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

  "php-8.1":
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

workflows:
    version: 2
    build:
        jobs:
            - "php-7.2"
            - "php-8.0"
            - "php-8.1"
